version: '3.8'

services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
    volumes:
      - pgdata:/var/lib/postgresql


  backend:
    build: .
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/app

volumes:
  pgdata:
